#!/usr/bin/env bash
# Rewrite the EndpointSlice with the workload's current instance addresses and
# apply it. Nothing on the platform does this for you, so run it after every
# deploy, restart, and rollback (register row L8).
#
#   deploy/datum/scripts/repoint-ingress.sh
#
# The operator watches EndpointSlices and reconciles every Gateway that
# references this one, so no Gateway or HTTPRoute change is needed.
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

need datumctl
need kubectl
need jq

SLICE_FILE="$DATUM_DIR/ingress/endpointslice.yaml"

info "reading instance addresses for workload $WORKLOAD"
# -o json dumps the full list before any --city filter is applied, so filter here.
ADDRS="$(datumctl compute instances --workload "$WORKLOAD" -o json \
  | jq -r '[.items[].status.networkInterfaces[0].assignments.externalIP | select(. != null and . != "")] | unique | .[]')"

[ -n "$ADDRS" ] || die "no external IPs found — check 'datumctl compute instances --workload $WORKLOAD'"

printf '%s\n' "$ADDRS" | sed 's/^/    /'

{
  printf '# Generated by deploy/datum/scripts/repoint-ingress.sh — do not hand-edit.\n'
  printf 'apiVersion: discovery.k8s.io/v1\n'
  printf 'kind: EndpointSlice\n'
  printf 'metadata:\n  name: %s\n' "$SLICE"
  printf 'addressType: IPv4\n'
  printf 'ports:\n  - name: http\n    protocol: TCP\n    appProtocol: http\n    port: %s\n' "$PORT"
  printf 'endpoints:\n'
  while IFS= read -r ip; do
    printf '  - addresses:\n      - %s\n' "$ip"
  done <<< "$ADDRS"
} > "$SLICE_FILE"

info "applying $SLICE_FILE"
kubectl apply -f "$SLICE_FILE"
